export const performance =[
    {
        id:'creatin',
        name:'Creatin Monohydrat',
        category:'Performans',
        price:1299,
        img:'https://www.hardlinenutrition.com/image/cache/catalog/enerji-guc/creapure500g_3d_01-500x500.png',
        description:"Kreatin insan vücudunda karaciğer ve böbrekte, üç temel amino asitin (arjinin, glisin, metionin) doğal olarak sentezlenmesi sonucunda oluşan doğal bir amino asit türevidir. Kreatinin en temel görevi ani ve güç gerektiren hareketlerde kaslara enerji sağlamaya yardımcı olmaktır. Kreatin kasların gerçek enerji kaynağı olan Adenosine triphosphate'nin miktarını artırmaya, dolayısıyla kreatin takviyesi gerçek bir güç artışı sağlamaya yardımcı olur.Antrenman sırasında, sürekli olarak Adenosine triphosphate üreten tek madde olması nedeniyle, Kreatin gerçek güç performansı artışı sağlayan tek sporcu gıdasıdır. Kreatin kısa süreli, yüksek yoğunluklu egzersizlerin ardı ardına yapılmasında fiziksel performansı arttırır. Faydalı etki,  günde 3 g kreatin alınması ile sağlanır.",
    },
    {
        id:'betalanine',
        name:'Beta Alanine 300 Gr',
        category:'Performans',
        price:325,
        img:'https://www.hardlinenutrition.com/image/cache/catalog/enerji-guc/betaalanine300g_3d_cizim%2001-500x500.png',
        description:"Beta-Alanin bir aminoasit türevidir.Son zamanlarda beta-alanin ‘in tüm ergojenik besin desteklerinden daha çok tercih edilmesinin altında yatan sebep ise iskelet kaslarında bulunan karnozin seviyesini arttırmaya yardımcı olmasıdır.",
    },
    {
        id:'taurine',
        name:'Taurine 300 Gr',
        category:'Performans',
        price:235,
        img:'https://www.hardlinenutrition.com/image/cache/catalog/enerji-guc/betaalanine300g_3d_cizim%2001-500x500.png',
        description:"Vücutta methionin ve sistin aminoasitlerinden sentezlenen yarı esansiyel bir amino asittir.",
    },
    {
        id:'preworkout',
        name:'Pre-Workout 1090 Gr',
        category:'Performans',
        price:1156,
        img:'https://www.hardlinenutrition.com/image/cache/catalog/Nox-2-yesil_elma-3d-500x500-500x500.png',
        description:"Karbonhidrat, çok çeşitli aminoasitler, vitamin ve mineraller ile zenginleştirilmiş, özel olarak formüle edilen bir üründür. Riboflavin (B2 Vitamini), Niasin, B6 Vitamini, B12 Vitamini ve Pantotenik asit normal enerji oluşum metabolizmasına katkıda bulunur.",
    },{
        id:'kgtkafein',
        name:'KGT KREATIN GLUTAMIN TAURIN 1000 Gr',
        category:'Performans',
        price:470,
        img:'https://www.hardlinenutrition.com/image/cache/catalog/enerji-guc/Kgt%20Yeni%20Ambalaj%20%203d_2-500x500.png',
        description:"Karbonhidrat, çok çeşitli aminoasitler, vitamin ve mineraller ile zenginleştirilmiş, özel olarak formüle edilen bir üründür. Riboflavin (B2 Vitamini), Niasin, B6 Vitamini, B12 Vitamini ve Pantotenik asit normal enerji oluşum metabolizmasına katkıda bulunur.",
    },
    {
        id:'arginine',
        name:'Arginine Liquid 1000 Ml',
        category:'Performans',
        price:850,
        img:'https://www.hardlinenutrition.com/image/cache/catalog/amino_asitler/arginine%20liquid_3d-500x500.png',
        description:"Bileşiminde her porsiyonda, 5000 mg Arjinin AKG, 750 mg Taurin, 250 mg L-Karnitin, 21 mg Vitamin B6, 200 mg Kafein içeren sıvı sporcu gıdasıdır. Antrenman öncesi kullanımı uygundur.",
    },
]